[package]
name = "sycamore-query"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sycamore = { version = "0.8", features = ["suspense"] }
fnv = "1"
weak-table = "0.3"
fluvio-wasm-timer = "0.2"